version: "3.8"

services:
  mitmproxy:
    image: mitmproxy/mitmproxy
    container_name: mitmproxy
    command: mitmweb --mode regular --listen-port 8080 --set web_host=0.0.0.0 --set web_port=8081 --set web_password=semgrep
    ports:
      - "8080:8080"  # HTTP proxy port
      - "8081:8081"  # Web UI port
    volumes:
      - ./mitmproxy-data:/home/mitmproxy/.mitmproxy
    networks:
      - semgrep-net

  semgrep:
    build:
      context: .
      dockerfile: Dockerfile.semgrep
    container_name: semgrep
    environment:
      HTTP_PROXY: http://mitmproxy:8080
      HTTPS_PROXY: http://mitmproxy:8080
    networks:
      - semgrep-net
    depends_on:
      - mitmproxy

networks:
  semgrep-net:
    driver: bridge

